language: node_js
node_js:
  - 14

# safelist
branches:
  only:
    - master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

services:
  - docker

before_install:
  - cd backend
  - npm install
  - docker build . -t movietest
  - docker images
  - docker tag movietest karmester/movietest:latest
  - docker login -u "karmester" --password ${DHUB_PASS}
  - docker push karmester/movietest:latest  

script:
  - npm test
