language: node_js
node_js:
  - "14"
services:
  - docker
before_install:
  - cd backend
  - docker build . -t example
  - docker images
  - docker tag karmester/example:latest
  - docker push karmester/example:latest

install:
  - npm install
script:
  - "true"
after_success:
  - npm run build
  - cd ..
  - bash ./deploy.sh
